SUBROUTINE GPU_BIND_JZ 

#ifdef _OPENACC
USE OPENACC
#endif
USE PARKIND1, ONLY : JPIM

IMPLICIT NONE

INTEGER (KIND=JPIM) :: NDEV, IDEV, IDTY

#ifdef _OPENACC

BLOCK
  CHARACTER*32 :: CLSLURM_LOCALID
  INTEGER :: ISLURM_LOCALID, IDEVTYPE, INUMDEVS
  IDEVTYPE = ACC_DEVICE_NVIDIA
  !$acc init
  CALL GETENV ('SLURM_LOCALID', CLSLURM_LOCALID)
  INUMDEVS = ACC_GET_NUM_DEVICES (IDEVTYPE)
  IF (CLSLURM_LOCALID == '') CLSLURM_LOCALID = '0'
  READ (CLSLURM_LOCALID, *) , ISLURM_LOCALID
  CALL ACC_SET_DEVICE_NUM (MOD (ISLURM_LOCALID, INUMDEVS), ACC_GET_DEVICE_TYPE ())
ENDBLOCK

#endif

END SUBROUTINE
